#!/usr/bin/env python3
"""Compile root reading copies from authoritative modular Markdown; no science computation."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs'


def root_links(text):
    def convert(match):
        target = match.group(1)
        if re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', target) or target.startswith(('#','/')):
            return match.group(0)
        if target.startswith('docs/'):
            return match.group(0)
        return '](' + 'docs/' + target + ')'
    return re.sub(r'\]\(([^)]+)\)', convert, text)


def joined(paths):
    return '\n\n---\n\n'.join(root_links(p.read_text(encoding='utf-8')).strip() for p in paths) + '\n'


def main():
    docs = sorted(DOCS.glob('[0-9][0-9]_*.md')) + [DOCS / 'SOURCES.md']
    intro = '''# Parallel Circulation Oxygen Explorer — complete specification v1.2

Version **1.2.0-spec**, 2026-09-18. This is the entire integrated coding-agent contract, not a completed application. Modular documents in `docs/` are authoritative. This file is generated by `scripts/compile_specification.py`.

The pack includes a runnable numerical reference pipeline. Barnea fixed-flow contracts, Ahmed-inspired indexed/criterion additions, and the new separately selected resistance provider are all retained. Normalized versus physical oxygen accounting and nominal versus circuit-secant closure are explicit. Source disagreements and unperformed source/browser/clinical gates remain visible.

---

'''
    (ROOT / 'FULL_SPECIFICATION.md').write_text(intro + joined(docs), encoding='utf-8')
    (ROOT / 'SAVORGNAN_EXTENSION_TICKET.md').write_text('''# Savorgnan extension ticket — v1.2

Use this ticket with the **entire unpacked bundle**, not in place of the original Barnea/Ahmed requirements. The complete contract is [FULL_SPECIFICATION.md](FULL_SPECIFICATION.md), the all-stage handoff is [IMPLEMENTATION_TICKET.md](IMPLEMENTATION_TICKET.md), and the executable reference entry point is `scripts/run_reference_pipeline.py`. This ticket includes the new scientific, visualization, pipeline and source-audit details in full.

---

''' + joined([DOCS / name for name in ('08_SAVORGNAN_RESISTANCE_EXTENSION.md','09_REFERENCE_PIPELINE.md','10_SAVORGNAN_SOURCE_AUDIT.md')]), encoding='utf-8')
    (ROOT / 'AHMED_EXTENSION_TICKET.md').write_text('''# Ahmed extension ticket — retained and integrated in v1.2

The original hemoglobin/indexing/criterion requirements are retained below, with their v1.2 integration note. For the complete build use [FULL_SPECIFICATION.md](FULL_SPECIFICATION.md) and [IMPLEMENTATION_TICKET.md](IMPLEMENTATION_TICKET.md); do not treat this historical amendment as the only current work order. Ahmed full-text replication remains separately gated.

---

''' + joined([DOCS/'07_AHMED_HEMOGLOBIN_EXTENSION.md']), encoding='utf-8')
    (ROOT / 'IMPLEMENTATION_TICKET.md').write_text('''# Complete implementation ticket and pipeline — v1.2

This is the entire dependency-ordered work order for a **new repository**. Keep the complete unpacked bundle with this file. Every scientific/UI detail in [FULL_SPECIFICATION.md](FULL_SPECIFICATION.md) is part of acceptance; the runnable verification workflow is included here, not promised as future work. The application itself is still to be implemented.

---

''' + (ROOT/'MASTER_IMPLEMENTATION_PROMPT.md').read_text() + '\n\n---\n\n' + joined([DOCS/'06_IMPLEMENTATION_TICKETS.md',DOCS/'09_REFERENCE_PIPELINE.md']), encoding='utf-8')
    print('Compiled full specification and three root ticket reading copies.')


if __name__ == '__main__':
    main()
